# Generated by Django 3.2.7 on 2021-10-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timups', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
